### ISSUE TITLE
'Order state wasn\'t changed to processing. Please check the order.' check is assuming the order is successful

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2-core#14]
Sometimes an order gets canceled which will fail this check but will have been what was intended.

**Comment by vinodsowdagar** [comment]
Hi @Hexmage , 

Thanks for the report.
Are you running the latest fix we released a couple of days ago? It should have fixed this issue.

**Comment by Hexmage** [comment]
@Vinod-MultiSafepay 

I was not. And I see you removed the check. In the latest version.

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

Yes, the functionality was not implemented correctly and we had to remove it with a hotfix.
This should be fixed now, therefore i am closing this.
