### ISSUE TITLE
Error during Setup:Upgrade: "Circular dependency: MultiSafepay\ConnectCore\Config\Config depends on MultiSafepay\ConnectCore\Logger\Handler and vice versa."

### ISSUE THREAD

**Issue by Hexmage** [MultiSafepay/magento2-core#16]
Strangely enough this error doesn't always happen. I've only had it with one of our webshops so far.

I did find the circular dependency though.
\MultiSafepay\ConnectCore\Config\Config -> \MultiSafepay\ConnectCore\Util\JsonHandler -> \MultiSafepay\ConnectCore\Logger\Logger -> vendor/multisafepay/magento2-core/etc/di.xml:7716 -> \MultiSafepay\ConnectCore\Logger\Handler -> \MultiSafepay\ConnectCore\Config\Config

So I'm honestly surprised that it's not happening more often

**Comment by vinodsowdagar** [comment]
Hi @Hexmage ,

Thank you for reporting this.

Really strange that this didn't show up before, but your findings seem to be correct..
I see that my colleague injected the JsonHandler inside the Config, but it is only being used to parse accountData, which is only used in the GenericConfigProvider, which already has a dependency on the JsonHandler anyway, so the parsing can happen there instead.

I have added this task to the backlog and expect it to be included in the next version of our plugin.

If you have any questions or comments in the meantime, let me know.

**Comment by thokiller** [comment]
Hi @Vinod-MultiSafepay ,

Do you have a update regarding the Circular dependency? (maybe a patch or commit change?)

We are currently facing this and it is preventing us from updating. 

Please let me know when this is resolved or if there is a temporary fix

**Comment by vinodsowdagar** [comment]
Hi @Hexmage and @thokiller ,

We have just released a new version of our module which fixes this issue:
https://github.com/MultiSafepay/magento2/releases/tag/2.17.0

For now i am closing this issue. If you still encounter issues or have other questions, feel free to reopen this.
