### ISSUE TITLE
Multiple calls to cancel orders since added settings

### ISSUE THREAD

**Issue by indykoning** [MultiSafepay/magento2-core#18]
Since commit https://github.com/MultiSafepay/magento2-core/commit/b050ea462a99b92a63872826c44cbe961d64212a
the option to set custom order statuses has been added.

For `expired`, `Declined`, `Cancelled`, and `Void` this defaults to `Canceled`
However in the code itself on line
https://github.com/MultiSafepay/magento2-core/commit/b050ea462a99b92a63872826c44cbe961d64212a#diff-4bf8073a912ab726ba27ba74e82d621b74357b36fc9c7d384d03f52b9d92ce45R145
https://github.com/MultiSafepay/magento2-core/commit/b050ea462a99b92a63872826c44cbe961d64212a#diff-4bf8073a912ab726ba27ba74e82d621b74357b36fc9c7d384d03f52b9d92ce45R152

the order already gets canceled, thus it will either cause duplicate cancellation events or your configuration on these statuses to be in vain.

As a bonus, the additional check for the expired order to only cancel it if it's pending payment or new is overshadowed by the configuration of always setting expired orders to canceled. So no matter what expired transactions will ALWAYS be canceled.

My proposed solution is to either get rid of the configuration options for these transaction statuses, or to completely migrate the cancel logic to the configuration. But i do not know how the Expired status should be handled in that case.

**Comment by danielcivit** [comment]
Hi @indykoning,

After two months, we didn't get a reply to the questions made on the related PR.  We are closing this GitHub issue due inactivity. Please, feel free to reopen it, if you are available to provide more information.
