### ISSUE TITLE
Payment logo's are very small

### ISSUE THREAD

**Issue by jesse-deboer** [MultiSafepay/magento2-core#21]
During the build of a checkout I noticed the payment logo's are very small. Maybe it's an option to also send them in `.svg` format next to the existing `.png` or send them also with a `2x` version?

https://github.com/MultiSafepay/magento2-core/tree/master/view/base/web/images

**Comment by vinodsowdagar** [comment]
Hi @jesse-deboer ,

Thank you for the report.

Great timing actually, we have added a task to the backlog just this week to switch to our CDN and retrieve the payment icons dynamically. As a merchant, you will have the option to choose between 1x, 2x or SVG.

When we have more information regarding the development of this feature, we will give you an update.

**Comment by vinodsowdagar** [comment]
Hi @jesse-deboer ,

We've created a new release where we introduced a feature to choose SVG icons from our CDN: https://github.com/MultiSafepay/magento2/releases/tag/3.3.0

I'm closing this issue for now, if there are more questions, feel free to leave a comment and we will reopen the issue.
