### ISSUE TITLE
Magento 2.4.6 needs Laminas

### ISSUE THREAD

**Issue by Stigmi-Stephane** [MultiSafepay/magento2-core#22]
Zend Framework is no longer supported.
We have to use Laminas :

Client\Client.php
Client\CurlAdapter.php
Util\VersionUtil.php

**Comment by danielcivit** [comment]
Hi @Stigmi-Stephane.

Can we continue with this conversation here, where are more people involved:

https://github.com/MultiSafepay/magento2/issues/48

I am closing this issue. But feel free to re-open it if you prefer continue the conversation here instead of the suggested thread
