### ISSUE TITLE
Error: Class "Zend_Http_Client" not found

### ISSUE THREAD

**Issue by slongiaru-dmind** [MultiSafepay/magento2-core#24]
Installing Magento 2.4.6 (CE/EE) some Zend dependencies are removed so the multisafepay/magento2 package must be upgraded:

`Error: Class "Zend_Http_Client" not found in /vendor/multisafepay/magento2-core/Util/VersionUtil.php:73`

**Comment by vinodsowdagar** [comment]
Hi @slongiaru-rblab , this one should be fixed since version 3.0.0:
https://github.com/MultiSafepay/magento2-core/releases/tag/3.0.0

We have removed all the dependencies on Zend_Http_Client.
Closing this one. If there are more related questions, let us know and we will reopen the issue.
