### ISSUE TITLE
Sleep 10 on intialization eats processtime

### ISSUE THREAD

**Issue by JeroenBoersma** [MultiSafepay/magento2-core#26]
I was do'ing research on a busy server and found that there where many long running processes for MSP notifications.
In our case they're eating up open processes and available threads.

A deeper investigation showed the coded I referenced and is the reason why captain slow was on the server.

I tried to find the reasoning for this, as processes will be handled async when doing requests it will still handle other processes so I cannot find why one wants to steal 10 seconds of servertime per request?

https://github.com/MultiSafepay/magento2-core/blob/02d641cbbe964d5a28dbe6e0275865e73ac4e4b2/Service/Process/DelayExecution.php#L32C17-L32C17
```php
            sleep(10);
```

Is this something we can disable, can I create a PR to remove this or patch it?

Thank you!

*edit: added code*

**Comment by vinodsowdagar** [comment]
Hi @JeroenBoersma ,

Thanks for creating the issue. 

Sometimes there are multiple webhooks coming in within the same second with different statuses doing different things with the order. To make sure that they are not trying to save the order at the same time and overwriting one another, we decided to add a delay in there for one of them. 10 seconds is a bit excessive, we are currently looking into another way to handle this.

You are free to remove or reduce it yourself ofcourse in the meantime.

We will keep you updated when we have changed and released this in a future version of the module.

**Comment by vinodsowdagar** [comment]
Hi @JeroenBoersma ,

We've changed this to a delay of one second and it will only happen for transactions that have the 'Completed' status. The fix has been released today: https://github.com/MultiSafepay/magento2/releases/tag/3.1.3

I'm hereby closing this issue. If there are any more related questions, feel free to leave a comment.
