### ISSUE TITLE
Bug in recurring payments for GraphQL 

### ISSUE THREAD

**Issue by Citizen4our** [MultiSafepay/magento2-core#27]
Hello, after updated to latest version, can't place order by recurring method, because missing customer.reference in API call https://docs.multisafepay.com/recipes/recurring-payments-subsequent-payments

So, this happens because there is no `tokenize` parameter in additional information for GraphQL case in condition ` $this->recurringDataUtil->shouldAddRecurringData($payment->getAdditionalInformation())` 
![image](https://github.com/MultiSafepay/magento2-core/assets/47303372/f492cede-0328-4ec5-857b-18844d83c8d8)

Relative commit:
https://github.com/MultiSafepay/magento2-core/commit/0ccee74704f580d6833397ada1f0c616b20ba48e#diff-dcf7889964e40e5bbbd184e9136d47de1ff4ed4e5d69af707b0fac6596ab18a6R125

**Comment by danielcivit** [comment]
Hi @Citizen4our 

Thanks for contacting us and for your report. 

We will look at this issue, fix it, and get back to you with more information.

**Comment by danielcivit** [comment]
Hi @Citizen4our.

Thanks for contacting us again. We were looking into this issue, but we are somehow confused.  

Is true there is a bug (currently fixed internally and pending a release in the next days), in the shouldAddRecurringData method, you just mentioned. We think this will fix the issue you are reporting. 

Could you explain how you think this is related to GraphQL?

**Comment by Citizen4our** [comment]
Hi @Daniel-MultiSafepay 
In my opinion, it looks like this: 
this `tokenize` parameter is set to additional information in the usual frontend when creating an order by recurring method, but it is not set anywhere for graphql flow. So, that's why changes in the [commit](https://github.com/MultiSafepay/magento2-core/commit/0ccee74704f580d6833397ada1f0c616b20ba48e#diff-dcf7889964e40e5bbbd184e9136d47de1ff4ed4e5d69af707b0fac6596ab18a6R125) break graphql flow

**Comment by vinodsowdagar** [comment]
Hi @Citizen4our ,

Recurring transactions were not implemented in the GraphQL module yet, so they wouldn't be working anyways. We are currently working on implementing tokenization through a payment component transaction request through GraphQL, but that one is still internally on the backlog. So it should have never worked in the first place.

You should be capable to place a non recurring transaction through the GraphQL module. That feature should be working like expected. If it is not working like expected, please leave a comment and we can reopen this ticket.
