### ISSUE TITLE
No API/Interface available for the retrieval of payment urls.

### ISSUE THREAD

**Issue by RaphaelBronsveld** [MultiSafepay/magento2-core#5]
Hi there,

We are currently using the old [module](https://github.com/MultiSafepay/Magento2Msp) to provide payment methods at the vuestorefront frontend. We used the [PaymentUrlInterface](https://github.com/MultiSafepay/Magento2Msp/blob/master/Api/PaymentUrlInterface.php) to fetch the payment url so that we could redirect to the proper url.

In the new version this doesn't seem available, are you guys planning to add pwa support again? We are aware of the multisafepay-magento2-graphql module, but this doesn't fit our needs and isn't going to work with a non-pwastudio pwa.

Thanks in advance!

Gr, Raphael

**Comment by vinodsowdagar** [comment]
Hi @RaphaelBronsveld ,

GraphQL is the standard for PWA Studio and also ScandiPWA. Vue Storefront is one of the few that still uses the REST API.

Currently the new plugin only supports GraphQL and supporting REST endpoints has not been on our planning. 

I have added it to the backlog, but it is not planned to be picked up in the near future. In the meantime, we recommend to investigate if it is possible to use GraphQL queries with Vue Storefront. 

I see that from version 1.4.0 it will also be possible to work with GraphQL out of the box:
https://docs.vuestorefront.io/v1/guide/basics/graphql.html

**Comment by RaphaelBronsveld** [comment]
Thank you for the response @Vinod-MultiSafepay, we'll discuss this further internally.
