### ISSUE TITLE
Cannot create credit memo from invoice

### ISSUE THREAD

**Issue by ghost** [MultiSafepay/magento2-core#6]
Hello,

In our new release we ran into an issue with creating a credit memo on the invoice. The error is "Warning: Invalid argument supplied for foreach()" at https://github.com/MultiSafepay/magento2-core/blob/30079a6343a49683940ab1c07fec419fbc1cbdf8/Gateway/Request/Builder/RefundTransactionBuilder.php#L177

When we log the $captureData variable it is NULL. Also when checking `sales_payment_transaction` table the `additional_information` column is often NULL.

Thanks in advance.

Kind regards, Arno Kristiaan

**Comment by vinodsowdagar** [comment]
Hi @arnopp ,

We just released a hotfix for this issue which should fix it:
https://github.com/MultiSafepay/magento2/releases/tag/2.12.2

Could you confirm this by updating to the latest release?

**Comment by ghost** [comment]
@Vinod-MultiSafepay Thanks for the quick patch, we will try it out and report back to you.

**Comment by ghost** [comment]
@Vinod-MultiSafepay The patch fixed it, credit memo's work again! Thanks.
